## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "hugo-story"
title = "Vermietung Hildegard"
copyright = "2025"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "https://vermietung-hildegard.at"
publishDir = "public"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------


[Params]
description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
logo = "images/banner.jpg"
favicon = true

[Params.social]
email = "cbabf3bbb8abd4eb14b4e009b80b24abb421f32439b4bb21b80be01cc4bb"
phone = "ff2219ec1a0cacec22ac23aca70c1a"

[Params.asset]
fontawesome_css = ["css/fontawesome.min.css"]
fontawesome_js = ["js/fontawesome.min.js"]